version: '3'

networks:
  backend:

volumes:
  db-data:

services:
  mysql:
    image: mysql:5.7.24
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=zXFgCrqwbE5BKdxD
      - MYSQL_USER=user
      - MYSQL_PASSWORD=KWHSZhpFwmMfNp3T
      - MYSQL_DATABASE=my_finance
    volumes:
      - db-data:/var/lib/mysql

  app:
    image: 748977760035.dkr.ecr.us-east-1.amazonaws.com/my-finance-backend:0.2.1
    networks:
      - backend
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=user
      - DB_PASS=KWHSZhpFwmMfNp3T
      - DB_NAME=my_finance
      - SECRET_KEY=2a94d1e631eb93ffc51041356cced91d4b01c827c66b4a15
      - AUTH_TOKEN_EXPIRY_DAYS=30

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      - backend
    depends_on:
      - app
