"""empty message

Revision ID: 07e1320fa4af
Revises: 2e9807e1a2d3
Create Date: 2018-12-16 20:59:04.997520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07e1320fa4af'
down_revision = '2e9807e1a2d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_name_account', 'categories', ['account_id', 'name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_name_account', 'categories', type_='unique')
    # ### end Alembic commands ###
