"""empty message

Revision ID: 34640938b3b2
Revises: c0e205249dec
Create Date: 2018-12-04 17:34:55.974684

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34640938b3b2'
down_revision = 'c0e205249dec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'category', 'accounts', ['account_id'], ['id'])
    op.drop_column('category', 'is_default')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('is_default', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'account_id')
    # ### end Alembic commands ###
