"""empty message

Revision ID: 5f3e18faca2b
Revises: 4ca57a80230b
Create Date: 2018-12-10 08:59:54.168386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f3e18faca2b'
down_revision = '4ca57a80230b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'account_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('transactions', 'category_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'category_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('transactions', 'account_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
