"""empty message

Revision ID: 963921ad149c
Revises: c123712c7985
Create Date: 2018-11-27 01:20:27.996263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963921ad149c'
down_revision = 'c123712c7985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('limit', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('accounts', sa.Column('account_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'account_type')
    op.drop_table('credit_accounts')
    # ### end Alembic commands ###
