"""empty message

Revision ID: c9301840c766
Revises: 07e1320fa4af
Create Date: 2018-12-19 16:12:23.165372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9301840c766'
down_revision = '07e1320fa4af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_name_type', table_name='categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('unique_name_type', 'categories', ['name', 'type'], unique=True)
    # ### end Alembic commands ###
