"""empty message

Revision ID: d725bee846ac
Revises: c9301840c766
Create Date: 2018-12-19 16:18:03.720180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd725bee846ac'
down_revision = 'c9301840c766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_name_type_account', 'categories', ['account_id', 'name', 'type'])
    op.drop_index('unique_name_account', table_name='categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('unique_name_account', 'categories', ['account_id', 'name'], unique=True)
    op.drop_constraint('unique_name_type_account', 'categories', type_='unique')
    # ### end Alembic commands ###
