"""empty message

Revision ID: e8f9c0243626
Revises: 9de0c99a51bb
Create Date: 2018-12-21 13:53:50.437114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8f9c0243626'
down_revision = '9de0c99a51bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saving_accounts', sa.Column('completed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saving_accounts', 'completed')
    # ### end Alembic commands ###
