"""empty message

Revision ID: f523aea02c93
Revises: b871f89b3ee9
Create Date: 2018-12-15 20:02:43.587856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f523aea02c93'
down_revision = 'b871f89b3ee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('post_transaction_balance', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'post_transaction_balance')
    # ### end Alembic commands ###
