"""empty message

Revision ID: ffeaa4610b23
Revises: 963921ad149c
Create Date: 2018-11-28 12:10:41.314414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffeaa4610b23'
down_revision = '963921ad149c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('duration', sa.Interval(), nullable=True))
    op.add_column('accounts', sa.Column('interest_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'interest_rate')
    op.drop_column('accounts', 'duration')
    # ### end Alembic commands ###
